# <font color="red"> ISAA PROJECT- </font> 18BIT0226

## MODEL - ADABOOST

***GRADIENT BOOSTING***  

<div style="background-color:rgb(253, 255, 135); "> Gradient boosting is a machine learning technique for regression and classification problems, which produces a prediction model in the form of an ensemble of weak prediction models, typically decision trees.</div>

## <font color="blue"> 2/3 DATASET </font> - LINUX PROCESS

********

### IMPORT THE LIBRARIES

In [2]:
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn
%matplotlib inline

In [3]:
data=pd.read_csv("Train_Test_Linux_dataset/Train_Test_Linux_process.csv")

In [4]:
data.head()

ts    PID  TRUN  TSLPI  TSLPU  POLI  NICE  PRI  RTPR  CPUNR Status  \
0  1556129658  52888     0      1      0  norm    20  100     0      0      0   
1  1556129738   2791     0      5      0  norm     0  120     0      0      0   
2  1556129778   2504     0      1      0  norm     0  120     0      2      0   
3  1556129788   3147     1     12      0  norm     0  120     0      1      0   
4  1556129798  52888     0      1      0  norm    20  100     0      0      0   

   EXC State   CPU             CMD  label type  
0    0     S  0.01            atop      1  dos  
1    0     S  0.00        nautilus      1  dos  
2    0     S  0.00  upstart-dbus-b      1  dos  
3    0     S  1.00           drone      1  dos  
4    0     S  0.01            atop      1  dos

In [5]:
# Size of the dataset
data.shape

(160112, 17)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160112 entries, 0 to 160111
Data columns (total 17 columns):
ts        160112 non-null int64
PID       160112 non-null int64
TRUN      160112 non-null int64
TSLPI     160112 non-null int64
TSLPU     160112 non-null int64
POLI      160112 non-null object
NICE      160112 non-null int64
PRI       160112 non-null int64
RTPR      160112 non-null int64
CPUNR     160112 non-null int64
Status    160112 non-null object
EXC       160112 non-null int64
State     160112 non-null object
CPU       160112 non-null float64
CMD       160112 non-null object
label     160112 non-null int64
type      160112 non-null object
dtypes: float64(1), int64(11), object(5)
memory usage: 20.8+ MB


In [7]:
data.describe()

ts            PID           TRUN          TSLPI  \
count  1.601120e+05  160112.000000  160112.000000  160112.000000   
mean   1.555145e+09    3256.037293       0.083092       3.916814   
std    8.816813e+05    2071.338868       0.284315       7.856580   
min    1.554219e+09    1007.000000       0.000000       0.000000   
25%    1.554419e+09    2533.000000       0.000000       1.000000   
50%    1.554619e+09    3058.000000       0.000000       1.000000   
75%    1.556223e+09    3793.000000       0.000000       4.000000   
max    1.556549e+09   53075.000000       9.000000      67.000000   

               TSLPU           NICE            PRI      RTPR          CPUNR  \
count  160112.000000  160112.000000  160112.000000  160112.0  160112.000000   
mean        0.001130       5.157471     111.654748       0.0       1.569351   
std         0.074001       8.722292      20.521090       0.0       1.245371   
min         0.000000       0.000000       0.000000       0.0       0.000000   
25%         0.000000       0.000000     100.000000       0.0       0.000000   
50%         0.000000       0.000000     120.000000       0.0       2.000000   
75%         0.000000      20.000000     120.000000       0.0       3.000000   
max        21.000000      20.000000     139.000000       0.0       5.000000   

                 EXC            CPU          label  
count  160112.000000  160112.000000  160112.000000  
mean        0.017663       0.038341       0.375437  
std         0.692833       0.188411       0.484237  
min         0.000000       0.000000       0.000000  
25%         0.000000       0.000000       0.000000  
50%         0.000000       0.000000       0.000000  
75%         0.000000       0.010000       1.000000  
max       100.000000       4.000000       1.000000

In [8]:
data.isnull().sum()

ts        0
PID       0
TRUN      0
TSLPI     0
TSLPU     0
POLI      0
NICE      0
PRI       0
RTPR      0
CPUNR     0
Status    0
EXC       0
State     0
CPU       0
CMD       0
label     0
type      0
dtype: int64

There are no null values in the dataset

In [9]:
data['CMD'].value_counts()

atop              40831
vmtoolsd           9304
apache2            8347
Xorg               5873
nautilus           5665
                  ...  
kworker/5:3-cg        1
<du>                  1
<dbus>                1
<atop.daily>          1
<aptitude>            1
Name: CMD, Length: 406, dtype: int64

##### <font color="blue"> Tried to see the unique values of the "CMD" column so that could go for better encoding option but found out that it has many values . So we need to go for Label Encoding.

In [10]:
data['label'].value_counts()

0    100000
1     60112
Name: label, dtype: int64

In [11]:
data['type'].value_counts()

normal       100000
ddos          10000
password      10000
scanning      10000
injection     10000
dos           10000
xss           10000
mitm            112
Name: type, dtype: int64

In [12]:
data['State'].value_counts()

S    145383
R      8583
E      4315
I      1590
D       129
Z       112
Name: State, dtype: int64

In [13]:
data['Status'].value_counts()

-     125604
0      29080
N       2759
NE      2620
NS        47
C          1
NC         1
Name: Status, dtype: int64

In [14]:
data['POLI'].value_counts()

norm    155797
0         2910
-         1405
Name: POLI, dtype: int64

### ENCODING THE CATEGORICAL FEATURES

In [15]:
# Label Encoding

from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()

# We have 5 columns whose data type is not float or int
# CMD ,type ,
data["CMD_Enc"]=LE.fit_transform(data.CMD)
data["type_Enc"]=LE.fit_transform(data.type)
data.drop(['CMD','type'],axis=1,inplace=True)

In [16]:
# One hot Encoding

from sklearn.preprocessing import  OneHotEncoder
OHE_cat_features = data.select_dtypes('object').columns
OH_encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')
OH_cols_train = pd.DataFrame(OH_encoder.fit_transform(data[OHE_cat_features]))
OH_cols_train.index = data.index
OH_cols_train.columns = OH_encoder.get_feature_names(OHE_cat_features)
data = data.join(OH_cols_train)

data.drop(OHE_cat_features, axis=1, inplace = True)
# This is used to drop all the Parent Colums as new Columns have been created with numerical data

In [17]:
data.head()

ts    PID  TRUN  TSLPI  TSLPU  NICE  PRI  RTPR  CPUNR  EXC  ...  \
0  1556129658  52888     0      1      0    20  100     0      0    0  ...   
1  1556129738   2791     0      5      0     0  120     0      0    0  ...   
2  1556129778   2504     0      1      0     0  120     0      2    0  ...   
3  1556129788   3147     1     12      0     0  120     0      1    0  ...   
4  1556129798  52888     0      1      0    20  100     0      0    0  ...   

   Status_N  Status_NC  Status_NE  Status_NS  State_D  State_E  State_I  \
0       0.0        0.0        0.0        0.0      0.0      0.0      0.0   
1       0.0        0.0        0.0        0.0      0.0      0.0      0.0   
2       0.0        0.0        0.0        0.0      0.0      0.0      0.0   
3       0.0        0.0        0.0        0.0      0.0      0.0      0.0   
4       0.0        0.0        0.0        0.0      0.0      0.0      0.0   

   State_R  State_S  State_Z  
0      0.0      1.0      0.0  
1      0.0      1.0      0.0  
2      0.0      1.0      0.0  
3      0.0      1.0      0.0  
4      0.0      1.0      0.0  

[5 rows x 30 columns]

In [18]:
data["type_Enc"].value_counts()

4    100000
7     10000
6     10000
5     10000
2     10000
1     10000
0     10000
3       112
Name: type_Enc, dtype: int64

In [19]:
y=data['type_Enc']

In [20]:
x=data.drop(['type_Enc'], axis=1)

## SCALING 

In [21]:
# # STANDARD SCALER

# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()

# # extract numerical attributes and scale it to have zero mean and unit variance  
# data_name=data.iloc[:,:-1]
# cols = data_name.columns
# sc_data = scaler.fit_transform(x)
# # turn the result back to a dataframe
# data = pd.DataFrame(sc_data, columns = cols)

In [22]:
#MIN MAX SCALER

mm_scaler = sklearn.preprocessing.MinMaxScaler()
data_name=data.iloc[:,:-1]
cols = data_name.columns
sc_data = mm_scaler.fit_transform(x)
# turn the result back to a dataframe
data = pd.DataFrame(sc_data, columns = cols)

In [23]:
data

ts       PID      TRUN     TSLPI  TSLPU  NICE       PRI  RTPR  \
0       0.819986  0.996409  0.000000  0.014925    0.0   1.0  0.719424   0.0   
1       0.820020  0.034263  0.000000  0.074627    0.0   0.0  0.863309   0.0   
2       0.820038  0.028751  0.000000  0.014925    0.0   0.0  0.863309   0.0   
3       0.820042  0.041100  0.111111  0.179104    0.0   0.0  0.863309   0.0   
4       0.820046  0.996409  0.000000  0.014925    0.0   1.0  0.719424   0.0   
...          ...       ...       ...       ...    ...   ...       ...   ...   
160107  0.013705  0.029001  0.000000  0.029851    0.0   0.0  0.863309   0.0   
160108  0.013707  0.033495  0.000000  0.044776    0.0   0.0  0.863309   0.0   
160109  0.013709  0.030268  0.000000  0.059701    0.0   0.0  0.863309   0.0   
160110  0.013711  0.028463  0.000000  0.029851    0.0   0.0  0.863309   0.0   
160111  0.013713  0.025351  0.000000  0.014925    0.0   0.0  0.863309   0.0   

        CPUNR  EXC  ...  Status_C  Status_N  Status_NC  Status_NE  Status_NS  \
0         0.0  0.0  ...       0.0       0.0        0.0        0.0        0.0   
1         0.0  0.0  ...       0.0       0.0        0.0        0.0        0.0   
2         0.4  0.0  ...       0.0       0.0        0.0        0.0        0.0   
3         0.2  0.0  ...       0.0       0.0        0.0        0.0        0.0   
4         0.0  0.0  ...       0.0       0.0        0.0        0.0        0.0   
...       ...  ...  ...       ...       ...        ...        ...        ...   
160107    0.0  0.0  ...       0.0       0.0        0.0        0.0        0.0   
160108    0.2  0.0  ...       0.0       0.0        0.0        0.0        0.0   
160109    0.4  0.0  ...       0.0       0.0        0.0        0.0        0.0   
160110    0.6  0.0  ...       0.0       0.0        0.0        0.0        0.0   
160111    0.2  0.0  ...       0.0       0.0        0.0        0.0        0.0   

        State_D  State_E  State_I  State_R  State_S  
0           0.0      0.0      0.0      1.0      0.0  
1           0.0      0.0      0.0      1.0      0.0  
2           0.0      0.0      0.0      1.0      0.0  
3           0.0      0.0      0.0      1.0      0.0  
4           0.0      0.0      0.0      1.0      0.0  
...         ...      ...      ...      ...      ...  
160107      0.0      0.0      0.0      1.0      0.0  
160108      0.0      0.0      0.0      1.0      0.0  
160109      0.0      0.0      0.0      1.0      0.0  
160110      0.0      0.0      0.0      1.0      0.0  
160111      0.0      0.0      0.0      1.0      0.0  

[160112 rows x 29 columns]

In [24]:
# plt.figure(figsize=(20,10))
# sns.heatmap(data.corr())

### SAMPLING

In [25]:
y.value_counts()

4    100000
7     10000
6     10000
5     10000
2     10000
1     10000
0     10000
3       112
Name: type_Enc, dtype: int64

In [26]:
import imblearn
# from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler

s_strategy = {0: 10000, 1: 10000, 2:10000, 3:10000, 4:100000, 5:10000}

# ru = RandomUnderSampler()
ro=RandomOverSampler(sampling_strategy='auto',random_state=1)
# Xres, yres = ru.fit_sample(data,y)

Xres1,yres1=ro.fit_resample(x,y)

# oversample = RandomOverSampler(sampling_strategy=0.75) #75% oversampling
# X_res, y_res= oversample.fit_resample(X_train,y_train)

In [27]:
yres1.value_counts()

7    100000
6    100000
5    100000
4    100000
3    100000
2    100000
1    100000
0    100000
Name: type_Enc, dtype: int64

In [28]:
from sklearn import model_selection
from sklearn.model_selection import StratifiedKFold,KFold,RepeatedStratifiedKFold,cross_val_score
from numpy import mean

### TRAIN TEST SPLIT

In [29]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(Xres1,yres1, test_size=0.25, random_state=42, stratify=yres1)

### MODEL -ADABOOST

In [30]:
from sklearn.ensemble import AdaBoostClassifier
model = AdaBoostClassifier(random_state=42)

In [34]:
import time 
time_start=time.clock()
model.fit(X_train, y_train)
print(model.score(X_test,y_test))

time_elapsed=(time.clock()-time_start)
print(time_elapsed)

C:\Users\hriti\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  


0.375
56.777735199999825


C:\Users\hriti\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  


0.00014519999990625365


C:\Users\hriti\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  
C:\Users\hriti\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [31]:
from sklearn.metrics import classification_report,confusion_matrix
from sklearn import metrics
from sklearn.metrics import accuracy_score, f1_score, auc, roc_curve, roc_auc_score

In [32]:
pred1=model.predict(X_test)

In [33]:
# The major diagonal represents the true values
confusion_matrix(y_test,pred1)

array([[    0,     0, 25000,     0,     0,     0,     0,     0],
       [    0,     0, 25000,     0,     0,     0,     0,     0],
       [    0,     0, 25000,     0,     0,     0,     0,     0],
       [    0,     0,     0, 25000,     0,     0,     0,     0],
       [    0,     0,     0,     0, 25000,     0,     0,     0],
       [    0,     0, 25000,     0,     0,     0,     0,     0],
       [    0,     0, 25000,     0,     0,     0,     0,     0],
       [    0,     0, 25000,     0,     0,     0,     0,     0]],
      dtype=int64)

In [34]:
def get_classification_report(y_test, pred1): 
    report = metrics.classification_report(y_test, pred1, output_dict=True)
    df_classification_report = pd.DataFrame(report).transpose()
    df_classification_report = df_classification_report.sort_values(by=['support'], ascending=False)
    
    return df_classification_report

C_R = get_classification_report(y_test, pred1)
print(C_R)

C:\Users\hriti\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision  recall  f1-score     support
macro avg      0.270833   0.375  0.285714  200000.000
weighted avg   0.270833   0.375  0.285714  200000.000
0              0.000000   0.000  0.000000   25000.000
1              0.000000   0.000  0.000000   25000.000
2              0.166667   1.000  0.285714   25000.000
3              1.000000   1.000  1.000000   25000.000
4              1.000000   1.000  1.000000   25000.000
5              0.000000   0.000  0.000000   25000.000
6              0.000000   0.000  0.000000   25000.000
7              0.000000   0.000  0.000000   25000.000
accuracy       0.375000   0.375  0.375000       0.375


### K FOLD CROSS VALIDATION

- ### KFold

In [31]:
model = AdaBoostClassifier(random_state=42)
def evaluate_model(model):
    
    KF=KFold(n_splits=10)
    score1 = cross_val_score(model, X_train, y_train, scoring='accuracy', cv=KF)
    
    list_scores=[mean(score1)]
    
    return list_scores

scores = evaluate_model(model)

In [32]:
names=["KFold"]
print("KFOLD CROSS VALIDATION SCORE")
print("------------------------------------")

for (i,j) in zip(scores,names):
    print(j,"-",round(i*100,2),'%')
   
    

KFOLD CROSS VALIDATION SCORE
------------------------------------
KFold - 37.28 %


#### All the type of Cross validation give the accuracy around 96.9%

## HYPER PARAMETRIC TUNING

In [35]:
params={'n_estimators': [200,300],
           'learning_rate': [0.01,0.015]}

In [36]:
from sklearn.model_selection import GridSearchCV

In [37]:
grid = GridSearchCV(AdaBoostClassifier(),params,refit=True,verbose=3)


In [38]:
# X_train.iloc[np.random.randint(low=0, high=450000, size=int(0.15 * 450000))]
# X_train1=X_train.sample(frac=0.35)
# y_train1=y_train.sample(frac=0.35)

In [39]:
X_train.shape
y_train.shape

(600000,)

In [40]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] learning_rate=0.01, n_estimators=200 ............................
[CV]  learning_rate=0.01, n_estimators=200, score=0.626, total= 2.4min
[CV] learning_rate=0.01, n_estimators=200 ............................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  2.4min remaining:    0.0s


[CV]  learning_rate=0.01, n_estimators=200, score=0.626, total= 2.4min
[CV] learning_rate=0.01, n_estimators=200 ............................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  4.9min remaining:    0.0s


[CV]  learning_rate=0.01, n_estimators=200, score=0.627, total= 2.6min
[CV] learning_rate=0.01, n_estimators=200 ............................
[CV]  learning_rate=0.01, n_estimators=200, score=0.627, total= 3.0min
[CV] learning_rate=0.01, n_estimators=200 ............................
[CV]  learning_rate=0.01, n_estimators=200, score=0.626, total= 2.8min
[CV] learning_rate=0.01, n_estimators=300 ............................
[CV]  learning_rate=0.01, n_estimators=300, score=0.703, total= 4.1min
[CV] learning_rate=0.01, n_estimators=300 ............................
[CV]  learning_rate=0.01, n_estimators=300, score=0.704, total= 3.7min
[CV] learning_rate=0.01, n_estimators=300 ............................
[CV]  learning_rate=0.01, n_estimators=300, score=0.703, total= 3.6min
[CV] learning_rate=0.01, n_estimators=300 ............................
[CV]  learning_rate=0.01, n_estimators=300, score=0.703, total= 3.6min
[CV] learning_rate=0.01, n_estimators=300 ............................
[CV]  

[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed: 61.1min finished


GridSearchCV(estimator=AdaBoostClassifier(),
             param_grid={'learning_rate': [0.01, 0.015],
                         'n_estimators': [200, 300]},
             verbose=3)

In [41]:
grid.best_params_


{'learning_rate': 0.01, 'n_estimators': 300}

In [42]:
grid.best_estimator_

AdaBoostClassifier(learning_rate=0.01, n_estimators=300)

In [43]:
grid_predictions = grid.predict(X_test)

In [44]:
from sklearn.metrics import classification_report,confusion_matrix

In [45]:
print(confusion_matrix(y_test,grid_predictions))

[[10948 13898     0     0     0    20   128     6]
 [    0 24062   436     0     0     0   502     0]
 [   49 17268  7560     0     0     0   123     0]
 [    0     0     0 20666     0   891     0  3443]
 [    0     0     0     0 25000     0     0     0]
 [    0     0     0     0     0 23410     0  1590]
 [  216     0     0     0     0     0 24784     0]
 [    0     0     0     0     0 20336     0  4664]]


In [46]:
print(classification_report(y_test,grid_predictions))

              precision    recall  f1-score   support

           0       0.98      0.44      0.60     25000
           1       0.44      0.96      0.60     25000
           2       0.95      0.30      0.46     25000
           3       1.00      0.83      0.91     25000
           4       1.00      1.00      1.00     25000
           5       0.52      0.94      0.67     25000
           6       0.97      0.99      0.98     25000
           7       0.48      0.19      0.27     25000

    accuracy                           0.71    200000
   macro avg       0.79      0.71      0.69    200000
weighted avg       0.79      0.71      0.69    200000

